config/routes.rb
AppMap::Application.routes.draw do

  get "home/index"

  resources :items do
    put 'update_automation'
    put 'update_manual'
  end

   root :to => 'home#index'

end

app/models/item.rb
class Item < ActiveRecord::Base
  attr_accessible :automated_test, :created, :manual_test, :name, :notes
  before_create :set_creation

  def set_creation
    self.created = Time.now
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  # GET /items
  # GET /items.json
  def index
    @items = Item.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @items }
    end
  end

  # GET /items/1
  # GET /items/1.json
  def show
    @item = Item.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @item }
    end
  end

  # GET /items/new
  # GET /items/new.json
  def new
    @item = Item.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @item }
    end
  end

  # GET /items/1/edit
  def edit
    @item = Item.find(params[:id])
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(params[:item])

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, :notice => 'Item was successfully created.' }
        format.json { render :json => @item, :status => :created, :location => @item }
      else
        format.html { render :action => "new" }
        format.json { render :json => @item.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /items/1
  # PUT /items/1.json
  def update
    @item = Item.find(params[:id])

    respond_to do |format|
      if @item.update_attributes(params[:item])
        format.html { redirect_to @item, :notice => 'Item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @item.errors, :status => :unprocessable_entity }
      end
    end
  end

  def update_automation
        @item = Item.find(params[:item_id])
        if params[:value] == 'True'
          @item.automated_test = true
        else
          @item.automated_test = false
        end

    respond_to do |format|
      if @item.save!
        format.json { render :json => "success" }
      else
        format.json { render :json => @item.errors, :status => :unprocessable_entity }
      end
    end
  end

  def update_manual
        @item = Item.find(params[:item_id])
        if params[:value] == 'True'
          @item.manual_test = true
        else
          @item.manual_test = false
        end

    respond_to do |format|
      if @item.save!
        format.json { render :json => "success" }
      else
        format.json { render :json => @item.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item = Item.find(params[:id])
    @item.destroy

    respond_to do |format|
      format.json { render :json => "success" }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/home/index.html.erb
<h1>AppMap</h1>

<%= link_to "Application Map", items_path %>

app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :notes %><br />
    <%= f.text_area :notes %>
  </div>
  <div class="field">
    <%= f.label :automated_test %><br />
    <%= f.check_box :automated_test %>
  </div>
  <div class="field">
    <%= f.label :manual_test %><br />
    <%= f.check_box :manual_test %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<h1>Application Map</h1>

<%= link_to 'New Item', new_item_path %>
<br />
<table id="application_map_table">
  <tr>
    <th></th>
    <th>Name</th>
    <th>Automated</th>
    <th>Manual</th>
    <th></th>
  </tr>

<% @items.each do |item| %>
  <tr id="item_<%= item.id %>" data-id="<%= item.id %>" >
    <td><%= link_to 'Edit', edit_item_path(item) %></td>
    <td class="name"><%= item.name %></td>
    <td class="automated true_false">
      <a href="#">
      <% if item.automated_test? %>
        <%= image_tag "true.png" %>
      <% else %>
        <%= image_tag "false.png" %>
      <% end %>
    </a>
    </td>
    <td class="manual true_false">
      <a href="#">
      <% if item.manual_test? %>
        <%= image_tag "true.png" %>
      <% else %>
        <%= image_tag "false.png" %>
      <% end %>
    </a>
    </td>
    <td><a class="delete" href="#">delete</a></td>
  </tr>
<% end %>
</table>

app/views/items/new.html.erb
<h1>New item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @item.name %>
</p>

<p>
  <b>Notes:</b>
  <%= @item.notes %>
</p>

<p>
  <b>Created:</b>
  <%= @item.created %>
</p>

<p>
  <b>Automated test:</b>
  <%= @item.automated_test %>
</p>

<p>
  <b>Manual test:</b>
  <%= @item.manual_test %>
</p>


<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Delete', @item, :method => :delete, :data => { :confirm => 'Are you sure?' } %>
<%= link_to 'Back', items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AppMap</title>
  <%= csrf_meta_tags %>

  <link rel="stylesheet" type="text/css" href="/stylesheets/main.css" />
  <script type="text/javascript" src="/javascripts/vendor/jquery-1.8.0.min.js" ></script>
</head>
<body>

<%= yield %>

</body>
  <script type="text/javascript" src="/javascripts/main.js" ></script>
</html>